name:  Howler Plugin

on: 
  push:
      branches-ignore:
      - 'master'
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        distribution: [ 'zulu', 'temurin' ]
        java: [ '11', '17' ]
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: '${{ matrix.java }}'
        distribution: '${{ matrix.distribution }}'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml -Djava_version=${{ matrix.java }}
    - name: Test with Maven
      run: mvn -B test --file pom.xml -Djava_version=${{ matrix.java }}
      
